# Generated by Django 3.2.8 on 2021-10-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarista',
            name='telefone',
            field=models.CharField(max_length=14),
        ),
    ]
